### ISSUE TITLE
BarFunnel chart won't render for ChartJS versions > 2.2.0

### ISSUE THREAD

**Issue by Tafkas** [chartjs/Chart.BarFunnel.js#2]
ChartJS 2.2.2 is the last version to work with the BarFunnel chart.

**Comment by Tafkas** [comment]
I just double checked. It works with ChartJS version 2.3.0 but the current release (2.4.0) does not.

**Comment by etimberg** [comment]
@jorgecgll can you take a look at this?

**Comment by etimberg** [comment]
I got it working here: http://jsbin.com/meqaloq/edit?html,js,output
The issue is that the internal `getBarWidth` and `calculateBarX` methods changed. Rather than individually calculate the ruler internally, they are now passed it. This change was made for performance reasons. I added comments where the changes were made.
